// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkp8vjC1qR9imkeBbWBRRBebHJVgDS8-w',
    appId: '1:316024946957:web:a50aedc4ade93e1878f044',
    messagingSenderId: '316024946957',
    projectId: 'smart-aquarium-d7b9c',
    authDomain: 'smart-aquarium-d7b9c.firebaseapp.com',
    databaseURL: 'https://smart-aquarium-d7b9c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-aquarium-d7b9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BhbaX2OWi5AlRarPZuKsxJvsBxTqiic',
    appId: '1:316024946957:android:544bc0c539b1311278f044',
    messagingSenderId: '316024946957',
    projectId: 'smart-aquarium-d7b9c',
    databaseURL: 'https://smart-aquarium-d7b9c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-aquarium-d7b9c.appspot.com',
  );
}
